### PR TITLE
boost: Add boost package.

### PR DESCRIPTION
**Pull request by AkitoTakada**
We built the following and confirmed that it can be executed.

```
#include <boost/version.hpp>
#include <iostream>

int main() {
    std::cout << BOOST_VERSION << "\n" // 104601
              << BOOST_LIB_VERSION "\n"; // 1_46_1
}
```
root@qemuarm64:~# vi version.cpp 
root@qemuarm64:~# /usr/bin/aarch64-emlinux-linux-g++ version.cpp 
root@qemuarm64:~# ./a.out 
106700
1_67

```
#include <iostream>
#include <limits>
#include <boost/math/constants/constants.hpp>

int main ()
{
    double pi = boost::math::constants::pi<double>();

    std::cout.precision(std::numeric_limits<double>::max_digits10);
    std::cout << pi << std::endl;
}
```
root@qemuarm64:~# vi pi.cpp 
root@qemuarm64:~# /usr/bin/aarch64-emlinux-linux-g++ pi.cpp 
root@qemuarm64:~# ./a.out 
3.1415926535897931

```
#include <iostream>
#include <boost/math/common_factor_rt.hpp>

int main()
{
    // 12と18の最大公約数を求める
    int result = boost::math::gcd(12, 18);

    std::cout << result << std::endl;
}
```
root@qemuarm64:~# vi gcd.cpp 
root@qemuarm64:~# /usr/bin/aarch64-emlinux-linux-g++ gcd.cpp 
root@qemuarm64:~# ./a.out 
6

### CODE REVIEW

**Comment by yuwata** [comment]
Why do you remove `context` and `coroutine` from `arm`?

I think it is better to add the following in .bb file and drop the .inc file if possible:
```
BOOST_LIBS += " signals"
BOOST_LIBS_append_arm = ""
BJAM_OPTS_append_arm = ""
```
But this is not tested, so I am not sure it works.

**Comment by AkitoTakada** [comment]
boost's debian recipe is based on version 1.67. Looking at the yocto base recipe, arm context and coroutine is supported at version 1.69.
The yocto recipe patch (22cbd08cb1b8fd61d296d1c136e433d26d73dfd5) was applied and the context and coroutine of the arm were supported, but the source code failed to build.
It seems that it cannot be supported in version 1.67 which is the base of debianization.

```
#include <boost/coroutine2/coroutine.hpp>
#include <iostream>

typedef boost::coroutines2::coroutine<int> coro_t;

int main()
{
  coro_t::pull_type source(
    [](coro_t::push_type & sink)
    {
      for (auto i = 0; i < 10; ++i)
        sink(i);
    });

  for (auto i : source)
    std::cout << i <<  " ";
}
```

```
root@qemuarm64:~# /usr/bin/aarch64-emlinux-linux-g++ ctest.cpp 
/usr/lib/gcc/aarch64-emlinux-linux/8.3.0/../../../../aarch64-emlinux-linux/bin/ld: /tmp/ccZ8TyS0.o: in function `boost::coroutines2::detail::pull_coroutine<int>::pull_coroutine<main::{lambda(boost::coroutines2::detail::push_coroutine<int>&)#1}, void>(main::{lambda(boost::coroutines2::detail::push_coroutine<int>&)#1}&&)':
ctest.cpp:(.text+0x124): undefined reference to `boost::context::stack_traits::default_size()'
/usr/lib/gcc/aarch64-emlinux-linux/8.3.0/../../../../aarch64-emlinux-linux/bin/ld: /tmp/ccZ8TyS0.o: in function `void* boost::context::detail::create_fiber2<boost::context::detail::fiber_record<boost::context::fiber, boost::context::basic_fixedsize_stack<boost::context::stack_traits>, boost::coroutines2::detail::pull_coroutine<int>::control_block::control_block<boost::context::basic_fixedsize_stack<boost::context::stack_traits>, main::{lambda(boost::coroutines2::detail::push_coroutine<int>&)#1}>(boost::context::preallocated, boost::context::basic_fixedsize_stack<boost::context::stack_traits>&&, main::{lambda(boost::coroutines2::detail::push_coroutine<int>&)#1}&&)::{lambda(boost::context::fiber&&)#1}>, boost::context::basic_fixedsize_stack<boost::context::stack_traits>, boost::context::fiber&&>(main::{lambda(boost::coroutines2::detail::push_coroutine<int>&)#1}, boost::context::basic_fixedsize_stack<boost::context::stack_traits>, boost::context::fiber&&)':
ctest.cpp:(.text+0x75c): undefined reference to `make_fcontext'
/usr/lib/gcc/aarch64-emlinux-linux/8.3.0/../../../../aarch64-emlinux-linux/bin/ld: ctest.cpp:(.text+0x798): undefined reference to `jump_fcontext'
/usr/lib/gcc/aarch64-emlinux-linux/8.3.0/../../../../aarch64-emlinux-linux/bin/ld: /tmp/ccZ8TyS0.o: in function `void boost::context::detail::fiber_entry<boost::context::detail::fiber_record<boost::context::fiber, boost::context::basic_fixedsize_stack<boost::context::stack_traits>, boost::coroutines2::detail::pull_coroutine<int>::control_block::control_block<boost::context::basic_fixedsize_stack<boost::context::stack_traits>, main::{lambda(boost::coroutines2::detail::push_coroutine<int>&)#1}>(boost::context::preallocated, boost::context::basic_fixedsize_stack<boost::context::stack_traits>&&, main::{lambda(boost::coroutines2::detail::push_coroutine<int>&)#1}&&)::{lambda(boost::context::fiber&&)#1}> >(boost::context::detail::transfer_t)':
ctest.cpp:(.text+0x87c): undefined reference to `jump_fcontext'
/usr/lib/gcc/aarch64-emlinux-linux/8.3.0/../../../../aarch64-emlinux-linux/bin/ld: ctest.cpp:(.text+0x8d8): undefined reference to `ontop_fcontext'
/usr/lib/gcc/aarch64-emlinux-linux/8.3.0/../../../../aarch64-emlinux-linux/bin/ld: /tmp/ccZ8TyS0.o: in function `boost::context::fiber::~fiber()':
ctest.cpp:(.text._ZN5boost7context5fiberD2Ev[_ZN5boost7context5fiberD5Ev]+0x50): undefined reference to `ontop_fcontext'
/usr/lib/gcc/aarch64-emlinux-linux/8.3.0/../../../../aarch64-emlinux-linux/bin/ld: /tmp/ccZ8TyS0.o: in function `boost::context::fiber::resume() &&':
ctest.cpp:(.text._ZNO5boost7context5fiber6resumeEv[_ZNO5boost7context5fiber6resumeEv]+0x58): undefined reference to `jump_fcontext'
collect2: error: ld returned 1 exit status
```

**Comment by masami256** [comment]
@AkitoTakada  How about add following setting in bb file? instead of have boost.inc locally.

```
BOOST_LIBS_remove_arm = "context coroutine"
BJAM_OPTS_remove_arm = "abi=aapcs architecture=arm"
```

**Comment by AkitoTakada** [comment]
I misunderstood the indication.
Changed boost.inc to use poky.

**Comment by masami256** [comment]
thanks!

**Pull request merged**
