### PR TITLE
Add polkit package.

### PR DESCRIPTION
**Pull request by L38s**
# Purpose of pull request

policykit

This pr adds policykit package based on meta-openembedded's /meta-oe/recipes-extended/polkit/polkit_0.104.bb

> When rebuilding the image after adding polkit to DISTRO_FEATURES, as described below, the dependency of DISTRO_FEATURES on polkit will cause the
> The systemd recipe that will be re-run from do_configure will cause an error in the do_install task, so you will need to execute the following command and process to clear SSTATE_CACHE.

# Test
## How to test

Check with qemuarm64.

Since polkit is required to be specified in the DISTRO_FEATURES variable in building polkit, add the following items to conf/local.conf to build core-image-minimal.

```
echo 'DISTRO_FEATURES_append =  " polkit " ' >> conf/local.conf
echo 'IMAGE_INSTALL_append = " polkit " ' >> conf/local.conf
```

Start qemuarm and type the command.

- pk-example-frobnicate
- pkaction
- pkexec
- pkttyagent
- polkitd

### pk-example-frobnicate
```
root@qemuarm64:~# pk-example-frobnicate
In pk-example-frobnicate
uid:           0
euid:          0
args:         `pk-example-frobnicate'
cwd:           /home/root
environment:
  USER=root
  SHLVL=1
  HOME=/home/root
  OLDPWD=/usr/bin
  HUSHLOGIN=FALSE
  PS1=\u@\h:\w\$
  LOGNAME=root
  TERM=vt102
  PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin
  HZ=100
  SHELL=/bin/sh
  PWD=/home/root
  EDITOR=vi
```

### pkaction
```
root@qemuarm64:~# pkaction
org.freedesktop.policykit.example.pkexec.run-frobnicate
org.freedesktop.policykit.exec
org.freedesktop.policykit.lockdown
```

### pkexec
```
root@qemuarm64:~# pkexec --version
pkaction version 0.105
```

### pkttyagent
```
root@qemuarm64:~#　pkttyagent --version
pkttyagent version 0.105
```

### polkitd
```
root@qemuarm64:~# /usr/libexec/polkitd
Entering main event loop
Connected to the system bus
Registering null backend at priority -10
Error getting login monitor: -2Using authority class PolkitBackendLocalAuthority
Acquired the name org.freedesktop.PolicyKit1
^CHandling SIGINT
Shutting down
Exiting with code 0
```

### CODE REVIEW

**Comment by masami256** [comment]
@L38s please provide polkit.service for systemd. It need systemd environment.

```
root@qemuarm64:~# pkexec  ls -la
Error getting authority: Error initializing authority: Error calling StartServiceByName for org.freedesktop.PolicyKit1: GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit polkit.service not found.
```

debian provide following unit file which is located in tmp-glibc/work/aarch64-emlinux-linux/polkit/0.105-r0/polkit-0.105/debian/polkit.service.

```
[Unit]
Description=Authorization Manager
Documentation=man:polkit(8)

[Service]
Type=dbus
BusName=org.freedesktop.PolicyKit1
ExecStart=/usr/lib/policykit-1/polkitd --no-debug
```

**Comment by L38s** [comment]
Fixed.
```
qemuarm64 login: root
root@qemuarm64:~# pkexec  ls -la
[   83.544727] random: polkitd: uninitialized urandom read (8 bytes read)
[   83.561387] random: polkitd: uninitialized urandom read (8 bytes read)
drwxr-xr-x    2 root     root          1024 Nov 29 05:59 .
drwxr-xr-x    3 root     root          1024 Nov 29 05:57 ..
-rw-------    1 root     root           261 Nov 29 06:54 .ash_history
```

**Comment by masami256** [comment]
@L38s polkit wasn't started and when I started it, I got following error.

```
qemuarm64 login: root
root@qemuarm64:~# PAGER=more systemctl status polkit
● polkit.service - Authorization Manager
   Loaded: loaded (/lib/systemd/system/polkit.service; static; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:polkit(8)
root@qemuarm64:~# systemctl start polkit
Job for polkit.service failed because the control process exited with error code.
See "systemctl status polkit.service" and "journalctl -xe" for details.
root@qemuarm64:~# PAGER=more systemctl status polkit
● polkit.service - Authorization Manager
   Loaded: loaded (/lib/systemd/system/polkit.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2021-11-30 04:01:38 UTC; 2s ago
     Docs: man:polkit(8)
  Process: 178 ExecStart=/usr/lib/policykit-1/polkitd --no-debug (code=exited, status=203/EXEC)
 Main PID: 178 (code=exited, status=203/EXEC)

Nov 30 04:01:38 qemuarm64 systemd[1]: Starting Authorization Manager...
Nov 30 04:01:38 qemuarm64 systemd[178]: polkit.service: Failed to execute command: No such file or directory
Nov 30 04:01:38 qemuarm64 systemd[178]: polkit.service: Failed at step EXEC spawning /usr/lib/policykit-1/polkitd: No such file or directory
Nov 30 04:01:38 qemuarm64 systemd[1]: polkit.service: Main process exited, code=exited, status=203/EXEC
Nov 30 04:01:38 qemuarm64 systemd[1]: polkit.service: Failed with result 'exit-code'.
Nov 30 04:01:38 qemuarm64 systemd[1]: Failed to start Authorization Manager.
```

**Comment by L38s** [comment]
Fixed.

**Comment by masami256** [comment]
@L38s Thanks!

**Pull request merged**
