### PR TITLE
add tcl and libical packages

### PR DESCRIPTION
**Pull request by yuwata**
But this includes an ugly workaround...

### CODE REVIEW

**Comment by masami256** [comment]
@yuwata  Both tcl and tcl-native build succeeded. However, I got following errors when I build core-image-minimal with ``` IMAGE_INSTALL_append += " tcl" ``` in conf/local.conf.  It seems path problem...

```
NOTE: Tainting hash to force rebuild of task /home/masami/release-test/repos/poky/meta/recipes-core/images/core-image-minimal.bb, do_build                                     | ETA:  0:00:00
WARNING: /home/masami/release-test/repos/meta-debian-extended/recipes-debian/tcltk/tcl_debian.bb.do_build is tainted from a forced run                                         | ETA:  0:00:00
WARNING: /home/masami/release-test/repos/poky/meta/recipes-core/images/core-image-minimal.bb.do_build is tainted from a forced run
Initialising tasks: 100% |#####################################################################################################################################################| Time: 0:00:00
Sstate summary: Wanted 46 Found 0 Missed 46 Current 730 (0% match, 94% complete)
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
WARNING: tcl-native-8.6.9-r0 do_populate_lic: Could not copy license file /home/masami/release-test/build/tmp-glibc/work/x86_64-linux/tcl-native/8.6.9-r0/tcl8.6.9/win/license.terms to /home/masami/release-test/build/tmp-glibc/work/x86_64-linux/tcl-native/8.6.9-r0/license-destdir/tcl-native/license.terms: [Errno 2] No such file or directory: '/home/masami/release-test/build/tmp-glibc/work/x86_64-linux/tcl-native/8.6.9-r0/tcl8.6.9/win/license.terms'
ERROR: tcl-native-8.6.9-r0 do_populate_lic: QA Issue: tcl-native: LIC_FILES_CHKSUM points to an invalid file: /home/masami/release-test/build/tmp-glibc/work/x86_64-linux/tcl-native/8.6.9-r0/tcl8.6.9/license.terms [license-checksum]
ERROR: tcl-native-8.6.9-r0 do_populate_lic: QA Issue: tcl-native: LIC_FILES_CHKSUM points to an invalid file: /home/masami/release-test/build/tmp-glibc/work/x86_64-linux/tcl-native/8.6.9-r0/tcl8.6.9/compat/license.terms [license-checksum]
ERROR: tcl-native-8.6.9-r0 do_populate_lic: QA Issue: tcl-native: LIC_FILES_CHKSUM points to an invalid file: /home/masami/release-test/build/tmp-glibc/work/x86_64-linux/tcl-native/8.6.9-r0/tcl8.6.9/library/license.terms [license-checksum]
ERROR: tcl-native-8.6.9-r0 do_populate_lic: QA Issue: tcl-native: LIC_FILES_CHKSUM points to an invalid file: /home/masami/release-test/build/tmp-glibc/work/x86_64-linux/tcl-native/8.6.9-r0/tcl8.6.9/macosx/license.terms [license-checksum]
ERROR: tcl-native-8.6.9-r0 do_populate_lic: QA Issue: tcl-native: LIC_FILES_CHKSUM points to an invalid file: /home/masami/release-test/build/tmp-glibc/work/x86_64-linux/tcl-native/8.6.9-r0/tcl8.6.9/tests/license.terms [license-checksum]
ERROR: tcl-native-8.6.9-r0 do_populate_lic: QA Issue: tcl-native: LIC_FILES_CHKSUM points to an invalid file: /home/masami/release-test/build/tmp-glibc/work/x86_64-linux/tcl-native/8.6.9-r0/tcl8.6.9/win/license.terms [license-checksum]
ERROR: tcl-native-8.6.9-r0 do_populate_lic: Fatal QA errors found, failing task.
ERROR: tcl-native-8.6.9-r0 do_populate_lic: 
ERROR: tcl-native-8.6.9-r0 do_populate_lic: Function failed: populate_lic_qa_checksum
ERROR: Logfile of failure stored in: /home/masami/release-test/build/tmp-glibc/work/x86_64-linux/tcl-native/8.6.9-r0/temp/log.do_populate_lic.22183
ERROR: Task (virtual:native:/home/masami/release-test/repos/meta-debian-extended/recipes-debian/tcltk/tcl_debian.bb:do_populate_lic) failed with exit code '1'
NOTE: Tasks Summary: Attempted 2594 tasks of which 2586 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  virtual:native:/home/masami/release-test/repos/meta-debian-extended/recipes-debian/tcltk/tcl_debian.bb:do_populate_lic
Summary: There were 4 WARNING messages shown.
Summary: There were 9 ERROR messages shown, returning a non-zero exit code.

```

**Comment by yuwata** [comment]
@masami256 Thank you for testing. PTAL.

**Comment by yuwata** [comment]
Also libical is added.

**Comment by masami256** [comment]
@yuwata  Run ``` bitbake -f tcl-native -c cleanall ``` then do ``` bitbake -f tcl-native ``` will get following errrors.

```
WARNING: tcl-native-8.6.9-r0 do_populate_lic: Could not copy license file /home/masami/release-test/build/tmp-glibc/work/x86_64-linux/tcl-native/8.6.9-r0/tcl8.6.9/../win/license.terms to /home/masam
i/release-test/build/tmp-glibc/work/x86_64-linux/tcl-native/8.6.9-r0/license-destdir/tcl-native/license.terms: [Errno 2] No such file or directory: '/home/masami/release-test/build/tmp-glibc/work/x8
6_64-linux/tcl-native/8.6.9-r0/tcl8.6.9/../win/license.terms'
ERROR: tcl-native-8.6.9-r0 do_populate_lic: QA Issue: tcl-native: LIC_FILES_CHKSUM points to an invalid file: /home/masami/release-test/build/tmp-glibc/work/x86_64-linux/tcl-native/8.6.9-r0/tcl8.6.9
/../license.terms [license-checksum]
ERROR: tcl-native-8.6.9-r0 do_populate_lic: QA Issue: tcl-native: LIC_FILES_CHKSUM points to an invalid file: /home/masami/release-test/build/tmp-glibc/work/x86_64-linux/tcl-native/8.6.9-r0/tcl8.6.9
/../compat/license.terms [license-checksum]
ERROR: tcl-native-8.6.9-r0 do_populate_lic: QA Issue: tcl-native: LIC_FILES_CHKSUM points to an invalid file: /home/masami/release-test/build/tmp-glibc/work/x86_64-linux/tcl-native/8.6.9-r0/tcl8.6.9
/../library/license.terms [license-checksum]
ERROR: tcl-native-8.6.9-r0 do_populate_lic: QA Issue: tcl-native: LIC_FILES_CHKSUM points to an invalid file: /home/masami/release-test/build/tmp-glibc/work/x86_64-linux/tcl-native/8.6.9-r0/tcl8.6.9
/../macosx/license.terms [license-checksum]
ERROR: tcl-native-8.6.9-r0 do_populate_lic: QA Issue: tcl-native: LIC_FILES_CHKSUM points to an invalid file: /home/masami/release-test/build/tmp-glibc/work/x86_64-linux/tcl-native/8.6.9-r0/tcl8.6.9
/../tests/license.terms [license-checksum]
ERROR: tcl-native-8.6.9-r0 do_populate_lic: QA Issue: tcl-native: LIC_FILES_CHKSUM points to an invalid file: /home/masami/release-test/build/tmp-glibc/work/x86_64-linux/tcl-native/8.6.9-r0/tcl8.6.9
/../win/license.terms [license-checksum]
ERROR: tcl-native-8.6.9-r0 do_populate_lic: Fatal QA errors found, failing task.
ERROR: tcl-native-8.6.9-r0 do_populate_lic: 
ERROR: tcl-native-8.6.9-r0 do_populate_lic: Function failed: populate_lic_qa_checksum
ERROR: Logfile of failure stored in: /home/masami/release-test/build/tmp-glibc/work/x86_64-linux/tcl-native/8.6.9-r0/temp/log.do_populate_lic.23136
ERROR: Task (virtual:native:/home/masami/release-test/repos/meta-debian-extended/recipes-debian/tcltk/tcl_debian.bb:do_populate_lic) failed with exit code '1'
NOTE: Tasks Summary: Attempted 90 tasks of which 82 didn't need to be rerun and 1 failed.
```
BTW, after the error, re-run ``` bitbake -f tcl-native ``` succeeded. It looks as if license check task runs before complete do_configure_prepend().

**Comment by yuwata** [comment]
@masami256 Finally I succeed to drop the ugly workaround. PTAL.

**Comment by masami256** [comment]
LGTM!  With latest patches, QA errors are disappeared.

**Pull request merged**
