### PR TITLE
Add gamin

### PR DESCRIPTION
**Pull request by AkitoTakada**
Because it disappeared from poky, it was created based on the past commit.

Confirmed to create a socket by starting gam_server. However, gamin's client that runs on the emulator cannot be prepared, and communication has not been confirmed.

```
/usr/libexec/gam_server -notimeout test &
ls /tmp/fam-root/
-> /tmp/fam-root/fam-test
```

### CODE REVIEW

**Comment by masami256** [comment]
@AkitoTakada could you merge fc05c68b54f10de2a9f6a96614785fd1d5257967 and a1e3d2d9674c1fa82865df31970b220c6d8c1404 to make simple add recipe patch?

**Comment by AkitoTakada** [comment]
Since the commit of a1e3d2d is a correction of typo and description miss, the contents of the recipe will not change.

**Comment by masami256** [comment]
> Since the commit of [a1e3d2d](https://github.com/miraclelinux/meta-debian-extended/commit/a1e3d2d9674c1fa82865df31970b220c6d8c1404) is a correction of typo and description miss, the contents of the recipe will not change.

Yes, it is. However, I mean is, adding gamin recipe, commit  fc05c68 and a1e3d2d  are merged into one single commit.  Because commit a1e3d2d is a kind of mid process to create new recipe so that it's not preferable to include such commit in repository history.

**Comment by AkitoTakada** [comment]
Then request from another branch add-gamin-2.

**Comment by yuwata** [comment]
You can use force-push.

**Comment by AkitoTakada** [comment]
Thank you for the way. force-pushed.

**Comment by masami256** [comment]
thanks.

**Pull request merged**
