### PR TITLE
glib-2.0: fix build error of nativesdk

### PR DESCRIPTION
**Pull request by hiraku-wfs**
This change should be removed when meta-debian support this.

Related: https://github.com/meta-debian/meta-debian/pull/183

### CODE REVIEW

**Comment by yuwata** [comment]
Why don't you use .bbappend file?

**Comment by hiraku-wfs** [comment]
You're right. I'll re-create the commit.

**Comment by hiraku-wfs** [comment]
I pushed the modified commit.

**Comment by masami256** [comment]
confirmed that build error has been fixed with the commit.

**Pull request merged**
