### PR TITLE
add net-snmp

### PR DESCRIPTION
**Pull request by mozoko**

### CODE REVIEW

**Comment by hiraku-wfs** [comment]
Patches are all same as meta-openembedded's ones?

**Comment by mozoko** [comment]
Yes, all files under recipes-debian/net-snmp/[net-snmp, files] are same as meta-openembedded's ones.

**Comment by mozoko** [comment]
For testing, I run ptest in this recipe.

Add below to local.conf
```
IMAGE_INSTALL_append = " net-snmp net-snmp-server-snmpd net-snmp-server-snmptrapd"
```

and, run ptest.

```
/usr/bin/ptest-runner net-snmp
```

Some tests failed like below.

```
Failed tests:
/usr/lib/net-snmp/ptest/testing/fulltests/default/T001snmpv1get_simple
/usr/lib/net-snmp/ptest/testing/fulltests/default/T0141snmpv2cset_simple
/usr/lib/net-snmp/ptest/testing/fulltests/default/T016snmpv2cgetfail_simple
/usr/lib/net-snmp/ptest/testing/fulltests/default/T017snmpv2ctov1getfail_simple
/usr/lib/net-snmp/ptest/testing/fulltests/default/T018snmpv1tov2cgetfail_simple
/usr/lib/net-snmp/ptest/testing/fulltests/default/T052snmpv2cinform_simple
/usr/lib/net-snmp/ptest/testing/fulltests/default/T161snmpTargetAddr_simpleSummary
```
But they can be ignored because PASS condition of testing included in net-snmp is wrong.
I downloaded net-snmp source package from [here](https://packages.ubuntu.com/source/xenial/net-snmp) and ran tests on my local environment(ubuntu 18.04) and got same result in all tests including above ones.
With explanation below, these failures due to bugs in testing and can be ignored.


### snmp-test-T001snmpv1get_simple
This test checks if the output log has just one string "Timeout" while some irrelevant lines has same string, which results in fail.
T001, T016, T017, T018 fails by same reason.

### T0141snmpv2cset_simple
The third test in T0141snmpv2cset_simple checks if the output log has a string
```
STRING: foobartestingbaz
```
while the output log has string like below
```
STRING: "foobartestingbaz"
```
and result in fail.

### T161snmpTargetAddr_simple
The third test in T161snmpTargetAddr_simple checks if the output log has a string

```
.1.3.6.1.6.3.12.1.2.1.6.65 = STRING: al.fa
```
while the output log has string like below
```
.1.3.6.1.6.3.12.1.2.1.6.65 = Hex-STRING: 61 6C 00 66 61
```
and "61 6C 00 66 61" means "al.fa".

### T052snmpv2cinform_simple
This test checks if the output log has just one string "Received" while some irrelevant lines in output log has same string, which results in fail.

**Comment by mozoko** [comment]
I confirmed that ptest errors in above comment can be ignored.
Because some MIB files in upstream don't satisfy DFSG, they have been stripped when importing to debian.
https://salsa.debian.org/debian/net-snmp/-/blob/master/debian/README.Debian-source

This causes ptest errors in above comment.
When I import all MIB files from upstream, all tests have passed.

**Comment by mozoko** [comment]
Here is the way to run ptest with MIB files in upstream:

mount built image
```
$ mkdir /tmp/cim
$ mount -o loop core-image-minimal-qemuarm64.ext4 /tmp/cim
```

fetch upstream source and copy MIBs into build image
```
$ wget https://downloads.sourceforge.net/net-snmp/net-snmp-5.7.3.tar.gz
$ tar xf net-snmp-5.7.3.tar.gz
$ cp  net-snmp-5.7.3/mibs/*.txt /tmp/cim/usr/lib/net-snmp/ptest/mibs/
```

unmount built image
```
$ sync
$ umount /tmp/cim
```

Then, runqemu the image, and run ptest .
```
$ runqemu qemuarm64 nographic

(after boot up)
# ptest-runner net-snmp
```

**Comment by hiraku-wfs** [comment]
Thank you!

**Pull request merged**
