### PR TITLE
Fix several CVEs

### PR DESCRIPTION
**Pull request by yuwata**

### CODE REVIEW

**Comment by hiraku-wfs** [comment]
Are these fixes excluded in Debian 10.2 packages?

**Comment by yuwata** [comment]
Not sure. Where can I check that?

**Comment by hiraku-wfs** [comment]
Debian 10.2 is planed to be released this weekend. So I'd like to consider if we should take these patches in after the release.

**Comment by yuwata** [comment]
Yeah. OK.

**Comment by yuwata** [comment]
@hiraku-wfs Updated. PTAL.

**Comment by hiraku-wfs** [comment]
Thanks!

**Pull request merged**
