### PR TITLE
quilt: fix ptest failure

### PR DESCRIPTION
**Pull request by yuwata**
The test requires ~12min, and ~15min seems enough.

### CODE REVIEW

**Comment by masami256** [comment]
@yuwata Does meta-debian have same issue?

**Comment by yuwata** [comment]
Yes. Poky should also have the same issue.

**Comment by masami256** [comment]
@yuwata quilt's recipes is in meta-debian, so would mind send pr to meta-debian please?

**Comment by yuwata** [comment]
Sure.

**Pull request closed without merging**
