### PR TITLE
Add OpenJDK 11

### PR DESCRIPTION
**Pull request by mozoko**

### CODE REVIEW

**Comment by mozoko** [comment]
# how to test openjdk-11

I confirmed that class file and jar file can be generated and executed as following.

Create Sample.java like below.
```
class Sample {
    public static void main(String[] args) {
        Sample2 sample = new Sample2();
    }
}
 
class Sample2 {
    public Sample2() {
        System.out.println("Hello Java!");
    }
}
```

Compile Sample.java and confirm that Sample.class and Sample2.class are generated.
```
root@qemuarm64:~# javac Sample.java
root@qemuarm64:~# ls
Sample.class   Sample.java    Sample2.class
```

Execute Sample.class
```
root@qemuarm64:~# java Sample
Hello Java!
```

Generate Sample.jar, which includes Sample.class and Sample2.class
```
root@qemuarm64:~# jar -cvf Sample.jar *.class
[  235.206264] random: jar: uninitialized urandom read (20 bytes read)
[  235.225831] random: jar: uninitialized urandom read (256 bytes read)
added manifest
adding: Sample.class(in = 287) (out= 218)(deflated 24%)
adding: Sample2.class(in = 351) (out= 263)(deflated 25%)

root@qemuarm64:~# echo "Main-Class: Sample" > manifest.mf
root@qemuarm64:~# jar -cvfm Sample.jar manifest.mf *.class
[  478.641650] random: jar: uninitialized urandom read (20 bytes read)
added manifest
adding: Sample.class(in = 287) (out= 218)(deflated 24%)
adding: Sample2.class(in = 351) (out= 263)(deflated 25%)

```

Execute Sample.jar
```
root@qemuarm64:~# java -jar Sample.jar
Hello Java!
```

**Comment by mozoko** [comment]
# how to test giflib

giflib has tests [here](https://github.com/mirrorer/giflib/tree/master/tests), but it is assumed to be run on the build host.
So, I built the source code on the target, and run the tests there as following.

* Add tools-sdk to EXTRA_IMAGE_EFATURES in local.conf , and run `bitbake core-image-minimal`.
* Run `bitbake giflib -c patch` on build host to get patched source.
* Run the image with `runqemu qemuarm64 nographic`.
* Take giflib source code directory (build/tmp-glibc/work/aarch64-emlinux-linux/giflib/5.1.4-r0/giflib-5.1.4) to the running image using scp.
* Build the giflib source code, and run tests on the running image.
```
$ cd giflib-5.1.4
$ ./autogen.sh
$ make check
```

here is the result.

```
make  check-TESTS
make[2]: Entering directory '/home/root/giflib-5.1.4'
make[3]: Entering directory '/home/root/giflib-5.1.4'
PASS: test.sh
============================================================================
Testsuite summary for giflib 5.1.4
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

**Comment by hiraku-wfs** [comment]
Thanks!
LGTM. I'll merge this after CI passes.

**Comment by mozoko** [comment]
# how to test lcms
Like giflib, lcms seems to assume tests to be run on the build host.
So, I bulit sources and ran tests on the target in the same way of giflib.


* Add tools-sdk to EXTRA_IMAGE_EFATURES in local.conf , and run `bitbake core-image-minimal`.
* Run `bitbake lcms -c patch` on build host to get patched source.
* Run the image with `runqemu qemuarm64 nographic`.
* Take lcms source code directory (build/tmp-glibc/work/aarch64-emlinux-linux/lcms/2.9-r0/lcms2-2.9) to the running image using scp.
* Build the lcms source code, and run tests on the running image.

```
$ cd lcms2-2.9
$ ./autogen.sh
$ make check
```


here is the result
[lcms-test.log](https://github.com/miraclelinux/meta-debian-extended/files/7601642/lcms-test.log)

**Pull request merged**
