### PR TITLE
glibc: Add locales package.

### PR DESCRIPTION
**Pull request by AkitoTakada**
Confirmed that the following commands work.

validlocale ja_JP.UTF-8
-> locale 'ja_JP.UTF-8' not available

mkdir /usr/lib/locale/
echo ja_JP.UFT-8 UTF-8 > /etc/locale.gen
locale-gen
locale -a
-> ja_JP.utf8

validlocale ja_JP.UTF-8
-> locale 'ja_JP.UTF-8' valid and available

update-locale LANG=ja_JP.UTF-8
cat /etc/default/locale
-> LANG=ja_JP.UTF-8

### CODE REVIEW

**Comment by masami256** [comment]
> Confirmed that the following commands work.
> 
> validlocale ja_JP.UTF-8
> -> locale 'ja_JP.UTF-8' not available
> 
> mkdir /usr/lib/locale/
> echo ja_JP.UFT-8 UTF-8 > /etc/locale.gen
> locale-gen
> locale -a
> -> ja_JP.utf8
> 

@AkitoTakada  How about create /usr/lib/local in do_install_append() ?
It seems debian locales package creates the directory([debian/debhelper.in/locales-all.dirs](https://salsa.debian.org/glibc-team/glibc/blob/sid/debian/debhelper.in/locales-all.dirs)).


> validlocale ja_JP.UTF-8
> -> locale 'ja_JP.UTF-8' valid and available
> 
> update-locale LANG=ja_JP.UTF-8
> cat /etc/default/locale
> -> LANG=ja_JP.UTF-8

**Comment by masami256** [comment]
@AkitoTakada When I run locale-gen command, I got following error. 

```
root@qemuarm64:~# locale-gen 
Generating locales (this might take a while)...
  ja_JP.UTF-8...locale alias file `/usr/share/locale/locale.alias' not found: No such file or directory
 done
Generation complete.
```
The locale.alias file is provideed by [locales package](https://packages.debian.org/buster/all/locales/filelist) in debian. so locales recipes provides it too?

**Comment by AkitoTakada** [comment]
Since the directory was deleted by do_poststash_install_cleanup (), the directory / usr / lib / locale is created by do_poststash_install_cleanup_append ().

Please add locales recipes.
IMAGE_INSTALL_append = "glibc-charmap- * glibc-localedata- *"

**Comment by masami256** [comment]
@AkitoTakada  what do you think of [this comment]( https://github.com/miraclelinux/meta-debian-extended/pull/136#issuecomment-527281082)?

**Comment by AkitoTakada** [comment]
Enabled to add locale.alias with the following command.
IMAGE_INSTALL_append = " glibc-locale-locale.alias"

**Comment by masami256** [comment]
@AkitoTakada could you merge  d5f411bec52269390c57c188044adcebc025df45 and e77ffb6abd9323cbb56173b808f54dbbbabeac59 ? then I'll merge this pr.

**Comment by AkitoTakada** [comment]
Merged the specified commits.

**Comment by masami256** [comment]
thanks

**Comment by masami256** [comment]
@AkitoTakada I'll revert this pr becase there is no recipe that provides locacles package(poky, openembedded-core, and etc). so please write independet recipe to create locales package.
However debian locales pacakge is built from glibc so that you can share the debian source package between glibc and locales recipes. In xorg-util directory, makedepend and util-macros does same thing.
Sorry for inconvinient.

**Pull request merged**
